### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by frensher** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#1]
hello，well job，but i can not find your paper？
can you put a link about your paper？

**Comment by frensher** [comment]
> hello，well job，but i can not find your paper？ can you put a link about your paper？
sorry  i have found

**Comment by w-lyy** [comment]
> 



> > hello，well job，but i can not find your paper？ can you put a link about your paper？
> > sorry  i have found

sorry，i can't find. could you post the link?

**Comment by Cihsaing** [comment]
@frensher  @w-lyy 
Hi, this paper had been published in 2022-06-28.
This is the link: https://ojs.aaai.org/index.php/AAAI/article/view/19911
