### ISSUE TITLE
the original mothed？

### ISSUE THREAD

**Issue by frensher** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#3]
hi，i want ask that what the original method ‘s training data and test data is?

**Comment by Cihsaing** [comment]
hi, if you mean the original methods of SOTA, which is fine-tuning in the normal images of FVRID_syn, and testing on the FVRID_syn and FVRID_real separately.

We can discuss further in Issues #2. 
Thank you!
