### ISSUE TITLE
datasets formate in FVRID_label.csv

### ISSUE THREAD

**Issue by xiaochi-learn** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#4]
In the VeriWild dataset, I cannot find the label for ORI_NAME in /Datasets/Preprocessing/_Split_Datasets/FVRID_Label.csv in the project. I wonder if this format is your own.

**Comment by Cihsaing** [comment]
@xiaochi-learn  
Thank you for your reminding, I have updated the whole annotation in the "/Datasets/Preprocessing/_Split_Datasets/FVRID_Label.csv". 
Please try again.  Wish all the best.
