### ISSUE TITLE
2_Depth_Estimation in preparing data

### ISSUE THREAD

**Issue by xiaochi-learn** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#5]
When preparing data and runing FVRID_SYN_***_prediction.m, i can not find the trained model (trained using the Make3D and NYUD2 datasets respectively) .

**Comment by Cihsaing** [comment]
@xiaochi-learn 
Hi, I found trained model of the depth estimation has been deleted by the original author.
So, I provides the weights of my record.
Link: https://drive.google.com/drive/folders/1cJtLa-3fSv4xSd-njEp3R4Ebz0uWjlrX?usp=sharing
