### ISSUE TITLE
Is this the latest code? 

### ISSUE THREAD

**Issue by xiaochi-learn** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#6]
Excuse me, is this the latest code? I trained this code and found that there are many errors in it, the syntax is wrong, and the running is different. Can you check to see if the code has not been updated in time.

**Comment by Cihsaing** [comment]
Hi, @xiaochi-learn .

Thanks for your suggestion.

I re-run all programs on the new RTX3090 device, and I found that there are many version conflicts with the newest torch version. Such as torch version conflict: amp and fft, etc. So I re-edited the training code with torch 1.12+, and I update the final version today, please kindly try again.

By the way, if you still meet some syntax problem, please using single gpu training and disable the "configs/FVRID_syn.yml": SOLVER.FP16.  

If you have any question, please let me know. 
By Aaron 08/26/2022.
