### ISSUE TITLE
pretrained model  download link  is wrong

### ISSUE THREAD

**Issue by sabrinamqq** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#7]
The pre-trained model can be downloaded from Link:
https://drive.google.com/file/d/1WhsvYQP-qg1R-BcpH5lonjxh4DYp2ouv/view?usp=sharing.
This link is the depth images( query_clear) , not the real pre-trained model.

**Comment by AaronCIH** [comment]
@sabrinamqq 
Hi, I open the link again, and it is shown as "best.pth".
![image](https://user-images.githubusercontent.com/91179422/198844064-0b8df79a-df83-47a9-830d-4a2d8ec38b64.png)

May I see your window to help more? Thanks!

**Comment by sabrinamqq** [comment]
> @sabrinamqq Hi, I open the link again, and it is shown as "best.pth". ![image](https://user-images.githubusercontent.com/91179422/198844064-0b8df79a-df83-47a9-830d-4a2d8ec38b64.png)
> 
> May I see your window to help more? Thanks!

This link is normal now, thanks
