### ISSUE TITLE
About DCNBlock

### ISSUE THREAD

**Issue by chen8573** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#8]
Hello, the author, what is the reason for using DCNBlock? How much MAP performance improvement can it bring?

**Comment by AaronCIH** [comment]
@chen8573 
HI, this is our implicit trick, we hope to add more dilated information for the different scale vehicles, and then DCN features will concat to the original embedding features; finally,  the channel attention will choose the suitable feature to calculate.

In our experiment, the improvement is not very obvious, I think it was dependent on the scale variance of the dataset.
